# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2799ee30c4c78dcb344718a4b98e1f5467f4c211bd9a3a2e525955d54ca8bc7b2ea85182837fc3e3b256257511b90bff8a289eb2b8b3cee519640bde56a356c9

test:
  secret_key_base: 6e75d77d44b70bb2a5c2d489f8375ef937b16ce8d989050b3cb33444d98b9625eccc5e24699d91da65124b3ae34fb042a659ae29589b5b9098ab3dd101d8ba39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
